# Generated by Django 4.1.7 on 2023-03-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre_interests',
            field=models.CharField(choices=[('science_fiction', 'Science Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
