# Generated by Django 4.1.7 on 2023-03-18 09:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_genre_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genre_interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('science_fiction', 'Science Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('other', 'Other')], max_length=15),
        ),
    ]
