# Generated by Django 4.1.7 on 2023-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_genre_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Up and Reading'),
            preserve_default=False,
        ),
    ]
