# Generated by Django 4.1.7 on 2023-03-19 06:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genre_interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('science_fiction', 'Science Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('adventure', 'Adventure'), ('horror', 'Horror'), ('dystopian', 'Dystopian')], max_length=40),
        ),
    ]
